name: Update Zenn Posts

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://zenn.dev/haya21_8/feed"
          max_post_count: 5
          readme_path: './README.md'
          comment_tag_name: "ZENN-POSTS"
